name: burp-scan

on:
  workflow_dispatch:

jobs:
  burp-dast-scan:
    name: burp dast scan
    permissions:
      checks: write
      contents: read
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3
      - name: run scan
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
