name: burp-scan

on:
  workflow_dispatch:

jobs:
  burp-dast-scan:
    name: burp dast scan
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      BURP_ENTERPRISE_API_KEY: ${{ secrets.BURP_API_KEY }}
      BURP_ENTERPRISE_SERVER_URL: ${{ secrets.BURP_URL }}
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3
      - name: run scan
        run: |
          SITE_NAME=`uuidgen` APPLICATION_URL=ginandjuice.shop BURP_ENTERPRISE_API_KEY=$BURP_ENTERPRISE_API_KEY BURP_ENTERPRISE_SERVER_URL=$BURP_ENTERPRISE_SERVER_URL sh run-scan.sh
